### ISSUE TITLE
ca_make_chromtab.pl

### ISSUE THREAD

**Issue by d-j-k** [cellgeni/cellatac#2]
Hi @micans 

I am just trying to set up the cellatac pipeline on openstack. Is it possible that `bin/ca_make_chromtab.pl` should be part of the repository?

Thank you,
Daniel

**Comment by micans** [comment]
Hi Daniel,
You are right, thanks.I have added it in master. This pipeline is still a fast-moving target. As it happens I will probably push a lot of changes soon (well, matter of between one and a few days) to support per-cluster cell-peak matrix building. I've developed this entirely locally however without pushing to github and it will probably get ploinked in master (fast moving etc). Let me know if there is something particular that you are interested in .... uhh you're at Sanger, right?

**Comment by d-j-k** [comment]
Hi Stijn,

Thank you for the quick reply and adding the file! I'm currently just doing some preliminary data analysis and was keen on using the multiplet recovery.
Good to know that the pipeline is still under heavy development, I will check back in a few weeks then. There might be a few things down the line (aka weeks/months) I would like to the pipeline, I will try to find you at the coffee stand up should that be the case.
